Repository thoth-station/lab, pull requests merged in 2019-03, with the labels that each got.

#100 Automatic update of dependency plotly from 3.6.1 to 3.7.0
  Pipfile.lock
Labels: bot

#101 Use Sphinx for documentation
  .gitignore
  README.rst
  docs/source/conf.py
  docs/source/index.rst
  setup.py
Labels: size/L

#102 Automatic update of dependency pandas from 0.24.1 to 0.24.2
  Pipfile.lock
Labels: bot

#104 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#105 Automatic update of dependency plotly from 3.7.0 to 3.7.1
  Pipfile.lock
Labels: bot

#99 Dynamic hierarchical layout
  .gitignore
  MANIFEST.in
  Pipfile
  Pipfile.lock
  requirements.txt
  setup.py
  thoth/lab/jupyter.py
  thoth/lab/viz/__init__.py
  thoth/lab/viz/assets/css/d3.css
  thoth/lab/viz/assets/js/dynamic/diagonal.js
  thoth/lab/viz/assets/js/static/diagonal.js
  thoth/lab/viz/js/__init__.py
  thoth/lab/viz/js/assets/css/d3.css
  thoth/lab/viz/js/dynamic/__init__.py
  thoth/lab/viz/js/static/__init__.py
  thoth/lab/viz/js/static/templates/diagonal.js
Labels: size/XXL

#106 Automatic update of dependency jupyter-require from 0.1.7 to 0.1.13
  Pipfile.lock
Labels: bot

#107 Automatic update of dependency plotly from 3.7.0 to 3.7.1
  Pipfile.lock
Labels: bot

#109 Automatic update of dependency gremlinpython from 3.4.0 to 3.4.1
  Pipfile.lock
Labels: bot

#108 Fix leftover from wrong rebase -- sphinx
  setup.py
Labels: approved, size/XS

#111 Account for jupyter-require API changes
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/lab/viz/__init__.py
  thoth/lab/viz/assets/css/d3.css
  thoth/lab/viz/assets/js/dynamic/diagonal.js
  thoth/lab/viz/assets/js/static/diagonal.js
Labels: approved, size/XL
