Repository thoth-station/lab, pull requests merged in 2019-07, with the labels that each got.

#130 Remove Gremlin imports
  thoth/lab/graph.py
Labels: approved, size/S

#131 Relock to remove old libraries
  Pipfile.lock
Labels: approved, size/L

#133 Release of version 0.1.1
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/XS

#134 Fix unintentional comments in requirements.txt
  requirements.txt
Labels: approved, size/XS

#135 Fix incorrect indexing in `groupby` method
  thoth/lab/underscore.py
Labels: size/XS
