Repository thoth-station/lab, pull requests merged in 2019-02, with the labels that each got.

#90 Update year in sources
  thoth/lab/graph.py
  thoth/lab/utils.py
Labels: size/XS

#92 Automatic update of dependency pandas from 0.23.4 to 0.24.1
  Pipfile.lock
Labels: bot

#94 Automatic update of dependency plotly from 3.5.0 to 3.6.1
  Pipfile.lock
Labels: bot

#95 Add str_join function to utils module
  thoth/lab/utils.py
Labels: approved, size/S

#96 Common jupyter utilities to customize environment
  thoth/lab/jupyter.py
Labels: approved, size/M

#97 Introduce dependency vizualization using d3.js
  thoth/lab/viz/__init__.py
  thoth/lab/viz/js/__init__.py
  thoth/lab/viz/js/assets/css/d3.css
  thoth/lab/viz/js/dynamic/__init__.py
  thoth/lab/viz/js/static/__init__.py
  thoth/lab/viz/js/static/templates/diagonal.js
Labels: approved, size/L

#98 Make sure all packages are installed
  setup.py
Labels: approved, size/XS
