Repository thoth-station/lab, pull requests merged in 2019-06, with the labels that each got.

#123 Minor fix to display correct release in title of docs html
  setup.py
Labels: approved, size/XS

#124 Move functionality from Amun Inspection notebook
  Pipfile
  Pipfile.lock
  thoth/lab/inspection.py
  thoth/lab/underscore.py
  thoth/lab/utils.py
Labels: approved, size/XXL

#128 Fix coala issues
  .coafile
  .thoth.yaml
  thoth/lab/convert.py
  thoth/lab/graph.py
  thoth/lab/inspection.py
Labels: size/S

#126 Release of version 0.1.0
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/L

#127 Zuul config
  .zuul.yaml
  Pipfile
  requirements.txt
Labels: approved, size/S
