Repository thoth-station/lab, pull requests merged in 2020-03, with the labels that each got.

#149 Release of version 0.1.2
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/S

#150 Release of version 0.1.3
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/L

#151 Release of version 0.1.4
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/L

#152 Automatic update of dependency ipython from 7.9.0 to 7.13.0
  Pipfile.lock
Labels: bot, size/XL

#153 Automatic update of dependency ipykernel from 5.1.3 to 5.1.4
  Pipfile.lock
Labels: bot, size/XS

#154 Automatic update of dependency pandas-profiling from 2.3.0 to 2.5.0
  Pipfile.lock
Labels: bot, size/XS

#155 Automatic update of dependency plotly from 4.2.1 to 4.5.4
  Pipfile.lock
Labels: bot, size/XS

#156 Automatic update of dependency cufflinks from 0.17.0 to 0.17.3
  Pipfile.lock
Labels: bot, size/XS

#157 Automatic update of dependency matplotlib from 3.1.1 to 3.2.0
  Pipfile.lock
Labels: bot, size/S

#158 Automatic update of dependency jupyter-require from 0.4.2 to 0.6.1
  Pipfile.lock
Labels: bot, size/XS

#159 Automatic update of dependency autopep8 from 1.4.4 to 1.5
  Pipfile.lock
Labels: bot, size/XS

#164 Automatic update of dependency matplotlib from 3.2.0 to 3.2.1
  Pipfile.lock
Labels: bot, size/L

#166 Remove coala-bears for conflict with faust
  Pipfile
  Pipfile.lock
Labels: approved

#165 Added amun inspection analysis functions
  thoth/lab/inspection.py
Labels: approved, size/L

#160 Extend functions due to change in Amun
  Pipfile
  Pipfile.lock
  thoth/lab/dependency_monkey.py
  thoth/lab/exception.py
  thoth/lab/inspection.py
  thoth/lab/inspection_report.py
Labels: size/XXL

#171 Release of version 0.1.5
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/S

#172 Modify requirements.txt
  requirements.txt
Labels: approved, size/XS

#174 Release of version 0.1.6
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/XS

#175 Automatic update of dependency ipykernel from 5.1.4 to 5.2.0
  Pipfile.lock
Labels: bot, size/S

#176 remove constraint on plotly
  requirements.txt
Labels: approved

#178 Release of version 0.1.7
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot

#162 Methods to analyze adviser results
  thoth/lab/adviser.py
Labels: approved, size/L

#181 Release of version 0.1.8
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/XS

#182 Correct minor errors in functions
  thoth/lab/inspection.py
  thoth/lab/inspection_report.py
Labels: size/M

#185 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.6
  Pipfile.lock
Labels: bot, size/L

#187 Automatic update of dependency thoth-storages from 0.22.6 to 0.22.7
  Pipfile.lock
Labels: bot, size/S
