Repository thoth-station/lab, pull requests merged in 2020-06, with the labels that each got.

#206 Add solver specific functions
  thoth/lab/common.py
  thoth/lab/solver.py
Labels: approved, size/L

#208 Correct docstring
  thoth/lab/inspection.py
Labels: approved, size/XS

#209 Release of version 0.1.11
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/S

#210 Adjust methods for plots and aggregation
  thoth/lab/__init__.py
  thoth/lab/adviser.py
  thoth/lab/common.py
  thoth/lab/graph.py
  thoth/lab/inspection.py
  thoth/lab/solver.py
  thoth/lab/viz/__init__.py
Labels: approved, size/XL

#204 Add check on retrieval
  thoth/lab/adviser.py
  thoth/lab/common.py
Labels: approved, size/M

#215 Release of version 0.1.12
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/L

#213 update the maintainer for release of thoth-lab
  .thoth.yaml
Labels: approved, size/XS

#216 Introduce security indicators analysis classes
  Pipfile.lock
  thoth/lab/adviser.py
  thoth/lab/common.py
  thoth/lab/inspection.py
  thoth/lab/security.py
  thoth/lab/solver.py
Labels: approved, size/XXL

#218 Release of version 0.2.0
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/XS

#219 Introduce security
  Pipfile
  Pipfile.lock
  thoth/lab/common.py
  thoth/lab/security.py
  thoth/lab/solver.py
Labels: approved, size/L

#221 Release of version 0.2.1
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/XS

#222 add store for inspection retrieval
  thoth/lab/common.py
  thoth/lab/inspection.py
Labels: approved, size/XS

#225 Correct SyntaxError
  thoth/lab/common.py
Labels: approved, size/XS

#224 Release of version 0.2.2
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/XS

#229 Move instantiation of classes
  thoth/lab/common.py
Labels: approved, size/M

#232 Release of version 0.2.3
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot

#233 Add methods for aggreagaation and correct instantiation
  thoth/lab/common.py
  thoth/lab/security.py
Labels: approved

#235 Release of version 0.2.4
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot

#238 Release of version 0.2.5
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot

#239 Include requirements.txt in distribution
  MANIFEST.in
Labels: approved

#241 Release of version 0.2.6
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: approved, bot
