Repository thoth-station/lab, pull requests merged in 2020-04, with the labels that each got.

#190 Substitute-package
  Pipfile
  Pipfile.lock
Labels: approved

#192 Move iplot initilization which is only for running in notebook
  thoth/lab/adviser.py
Labels: size/S

#194 Automatic update of dependency plotly from 4.5.4 to 4.6.0
  Pipfile.lock
Labels: bot, size/L

#195 Release of version 0.1.9
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/XS

#196 Add missing package to requirements.txt
  requirements.txt
Labels: approved, size/XS

#198 Fixes needed to make the release happen
  README.rst
  setup.py
Labels: approved, size/XS

#200 Release of version 0.1.10
  CHANGELOG.md
  thoth/lab/__init__.py
Labels: bot, size/XS

#201 Use RHEL 8
  .thoth.yaml
Labels: approved, size/XS
